### ISSUE TITLE
when mixed with Drag Ruler, Even sized tokens (2x2, 4x4) get placed center on a single space.

### ISSUE THREAD

**Issue by Iankid** [kandashi/easy-ruler-scale#4]
This creates the results of them be centered off main grid for their size

**Comment by kandashi** [comment]
I cannot replicate this in my testing with only ERS enabled, can you show a gif or example of this happening with *only* ERS

**Comment by Iankid** [comment]
Sorry it took a bit to get back. It's not an issue with Only ERS, it's when it's combined with at least 2 of these listed mods.

![Gridissue](https://user-images.githubusercontent.com/60759323/126018819-653e35e0-7528-41ea-a856-5d755f1ff4a8.png)

**Comment by kandashi** [comment]
It seems to be Drag Ruler + libWrapper

**Comment by kandashi** [comment]
We both seem to touch some of the same functions, which causes these issues
