### ISSUE TITLE
Toolset is stuck on the Measure Distance function

### ISSUE THREAD

**Issue by rtschaefer** [kandashi/easy-ruler-scale#8]
**Describe the bug**
After (1) activating the Easy Ruler Scale module, (2) changing the scale size of the ruler in the settings, and (3) using the Measure Distance tool, the Select Token tool is then stuck on the Ruler function (i.e. Measure Distance). I had to disable the module to get the Select Token functionality (the standard left click and hold operation) to work properly. 

**Expected behavior**
When the Measure Distance function tool is changed out for the Select Token tool, the Ruler should be disabled, and the ability to select tokens with a standard left click and drag restored. 

**Screenshots**

**Environment:**
 - OS: Windows 11
 - Browser Chrome (Current update)
 - Foundry Version 9 (Build 242)
 - Module Version 0.1.02
 - All Modules Disabled: No

Active Modules:
----------
5E Custom Currency v1.3.5;
Active Token Effects v0.3.05;
Adventure Music v1.1.0;
Ambiences Volume 2 - Michael Ghelfi v1.1;
Ambient Doors v2.2.6;
Automated Animations v1.1.6;
Backgroundless Pins v1.2.03;
Baileywiki Maps Pack v0.2.7;
Baileywiki Maps Premium v0.2.9;
Baileywiki Maps Towns v0.3.5;
Better Rolls for 5e v1.7.1;
Better Roll Tables v1.8.95;
Better Roofs v1.3.8;
Beyond20 companion module v1.4.0;
Candlekeep Mysteries v0.1.0;
Changelogs & Conflicts v0.7.7;
Combat Utility Belt v1.8.0;
CommunityLighting by Blitz v0.4.7;
Compendium Folders v2.4.1;
CoS - Wolf Den v1.0.1;
Cursor Hider v1.3.0;
Custom Nameplates v2.1.0;
D&D Beyond Importer v2.7.7;
DFreds Convenient Effects v1.16.0;
DFreds Droppables v1.4.0;
Dice So Nice! v4.3.1;
Dice Tray v1.4.1;
DNDBeyond Character Sheet for 5E v1.8.2;
DNDBeyond NPC Sheet v1.3.6;
Domille's Wondrous Works - Battlemap Collection v1.2.1;
Dragonshorn Tales - Encounters Volume 1 (5e/3.5e) v1.8.2;
Dynamic effects using Active Effects v0.8.76;
Easy Target v2.14;
Enhanced Terrain Layer v1.0.36;
Forien's Easy Polls v0.1.2;
Forien's Quest Log v0.7.9;
Foundry Community Tables v9.1;
FXMaster v2.2.0;
Game Audio Bundle 1 v2.8;
Game Audio Bundle 2 v2.8;
GM Notes v0.5.0;
Hey, Wait! v0.6.3;
Jack Kerouac's Animated Spell Effects v0.6.8;
JB2A - Patreon Complete Collection v0.3.4;
Jitsi WebRTC client v0.6.5;
Laptop Form Fix v0.0.8;
Let Me Roll That For You! v1.24;
Levels v2.4.4;
libCaptions v0.1.4;
lib - Color Settings v2.8.2;
Lib: Document Sheet Registrar v1.0.0;
Library: Scene Packer v2.4.0-alpha-3;
libWrapper v1.11.2.0;
Lock View v1.5.0;
Loot Sheet NPC 5e v3.4.1;
Magic Items v2.2.0;
Michael Ghelfi Studios Audio Pack v1.3;
Midi QOL v0.8.102;
Monk's Active Tile Triggers v1.0.48;
Monk's Hotbar Expansion v1.0.12;
Monk's Little Details v1.0.43;
Monk's Scene Navigation v1.0.21;
Monk's TokenBar v1.0.59;
Monster Manual v0.1.0;
Moonlight Maps v1.1.0;
Mordenkainen's Fiendish Folio Volume 1 v0.1.0;
Multilevel Tokens v1.5.2;
Permission Viewer v0.9.1;
PnP - Pointer and Pings! v2.3.4;
PopOut! v2.4;
Popout Resizer v1.4.2;
Quick Encounters v0.9.6;
QuickScale v1.3.0;
Search Anywhere v2.3.2;
Sequencer v1.3.5;
Settings Extender v1.2.0;
Simple Calendar vv1.3.75;
Simplefog - Manual Fog of War v0.1.18;
socketlib v1.0.10;
SoundBoard by Blitz v1.5.3;
Tabletop RPG Music v1.5.1;
Tasha’s Cauldron of Everything v0.1.0;
The MAD Cartographer | Free Battlemap Pack v1.0.1;
The Wild Beyond the Witchlight v0.1.0;
Tidy5e Sheet v0.5.21;
Tidy UI - Game Settings v0.1.30;
Times Up v0.8.31;
Token Action HUD v2.0.10;
Token Attacher v4.3.1;
Token Auras v1.15;
Tokenizer v3.5.0;
Token Magic FX v0.5.2.3;
Token Mold v2.14.0;
Trigger Happy v0.8.32;
Virtual Tabletop Assets - D&D Beyond Integration v3.3.5;
Volo's Guide to Monsters v0.1.0;
VTTA Core v2.0.3;
VTTA D&D Beyond Integration v2.0.11;
VTTA Tokens v2.0.5;
Wall Height v3.6.0.2;
WebRTC Tweaks v0.6.0;
Xanathar's Guide to Everything v0.1.0;
Your Tokens Visible v2.7.0;

**Comment by kandashi** [comment]
Cannot reproduce on v9 with version 0.1.02. Please try with *just* ERS to confirm that it is this module. If you cannot replicate, then the Find the Culprit module will help with debugging which of your many modules has the conflict
